version: '3'
services:
  server:
    image: vrspace
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - /app/server/target
      - /app/vrspace.db
      - .:/app/